"""LLM-based fix suggestion for complex issues.

This module provides LLM-powered fix generation for issues that don't have
rule-based fixes, using code context to generate appropriate solutions.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from src.infrastructure.llm.adapters import (
    LLMProvider,
    create_llm_provider_from_env,
    create_llm_provider,
    RateLimitError,
    ServiceUnavailableError,
    calculate_cost,
)

logger = logging.getLogger(__name__)


FIX_PROMPT_TEMPLATE = """You are a code review assistant. Generate a fix for the following issue.

**Issue:**
- Rule: {rule_id}
- Severity: {severity}
- Message: {message}

**Code Location:**
{file_path}:{line}

**Original Code:**
```{language}
{original_code}
```

**Surrounding Context:**
```{language}
{surrounding_code}
```

**Task:**
1. Explain the issue briefly
2. Provide the corrected code
3. Provide alternative solutions if applicable

Format your response as:
EXPLANATION: <brief explanation>
FIX: <corrected code>
ALTERNATIVES: <alternative solutions or "None">
CONFIDENCE: <confidence score 0.0-1.0>
"""


@dataclass
class LLMFixSuggestion:
    """Fix suggestion generated by LLM.

    Attributes:
        original_code: The original problematic code
        suggested_code: The LLM-generated fix
        explanation: Explanation of the fix
        confidence: Confidence score (0.0-1.0)
        alternative_suggestions: Alternative solutions if available
        rule_id: Associated rule ID
    """
    original_code: str
    suggested_code: str
    explanation: str
    confidence: float = 0.8
    alternative_suggestions: list[str] = field(default_factory=list)
    rule_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "original_code": self.original_code,
            "suggested_code": self.suggested_code,
            "explanation": self.explanation,
            "confidence": self.confidence,
            "alternatives": self.alternative_suggestions,
            "rule_id": self.rule_id,
        }


@dataclass
class LLMSuggestionStats:
    """Statistics for LLM suggestion calls.

    Attributes:
        total_calls: Total number of LLM calls made
        successful_calls: Number of successful calls
        failed_calls: Number of failed calls
        total_tokens: Total tokens consumed
        total_cost: Total cost in USD
    """
    total_calls: int = 0
    successful_calls: int = 0
    failed_calls: int = 0
    total_tokens: int = 0
    total_cost: float = 0.0

    def record_success(self, tokens: int, cost: float) -> None:
        """Record a successful call.

        Args:
            tokens: Number of tokens used
            cost: Cost in USD
        """
        self.total_calls += 1
        self.successful_calls += 1
        self.total_tokens += tokens
        self.total_cost += cost

    def record_failure(self) -> None:
        """Record a failed call."""
        self.total_calls += 1
        self.failed_calls += 1

    @property
    def success_rate(self) -> float:
        """Calculate success rate."""
        if self.total_calls == 0:
            return 0.0
        return self.successful_calls / self.total_calls

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "total_calls": self.total_calls,
            "successful_calls": self.successful_calls,
            "failed_calls": self.failed_calls,
            "total_tokens": self.total_tokens,
            "total_cost": round(self.total_cost, 6),
            "success_rate": round(self.success_rate, 2),
        }


@dataclass
class CodeContext:
    """Context for LLM fix generation.

    Attributes:
        file_path: Path to the source file
        function_name: Name of containing function (if known)
        surrounding_lines: Lines around the issue
        imports: Import statements in the file
        language: Programming language
    """
    file_path: str
    function_name: Optional[str] = None
    surrounding_lines: list[str] = field(default_factory=list)
    imports: list[str] = field(default_factory=list)
    language: str = "python"

    def get_relevant_code(self, target_line: int, context_lines: int = 3) -> str:
        """Get code around the target line.

        Args:
            target_line: Target line number (1-based)
            context_lines: Number of context lines to include

        Returns:
            Relevant code as string
        """
        if not self.surrounding_lines:
            return ""

        start = max(0, target_line - context_lines - 1)
        end = min(len(self.surrounding_lines), target_line + context_lines)
        return "\n".join(self.surrounding_lines[start:end])

    def get_surrounding_code(self, max_lines: int = 20) -> str:
        """Get surrounding context.

        Args:
            max_lines: Maximum lines to return

        Returns:
            Surrounding code as string
        """
        if not self.surrounding_lines:
            return ""

        lines = self.surrounding_lines[:max_lines]
        return "\n".join(lines)

    @classmethod
    def from_file(
        cls,
        file_path: str | Path,
        target_line: Optional[int] = None,
        context_lines: int = 10,
    ) -> "CodeContext":
        """Create CodeContext from a file.

        Args:
            file_path: Path to the source file
            target_line: Target line to focus on
            context_lines: Lines of context to include

        Returns:
            CodeContext instance
        """
        file_path = Path(file_path)

        try:
            content = file_path.read_text(encoding="utf-8", errors="replace")
            lines = content.split("\n")
        except OSError:
            return cls(file_path=str(file_path), language="python")

        language = cls._detect_language(file_path)
        imports = cls._extract_imports(content)

        if target_line:
            start = max(0, target_line - context_lines - 1)
            end = min(len(lines), target_line + context_lines)
            surrounding = lines[start:end]
            function_name = cls._extract_function_name(lines, target_line - 1)
        else:
            surrounding = lines[:50]
            function_name = None

        return cls(
            file_path=str(file_path),
            function_name=function_name,
            surrounding_lines=surrounding,
            imports=imports,
            language=language,
        )

    @staticmethod
    def _detect_language(file_path: Path) -> str:
        """Detect programming language from file extension."""
        ext_map = {
            ".py": "python",
            ".js": "javascript",
            ".ts": "typescript",
            ".jsx": "javascript",
            ".tsx": "typescript",
            ".c": "c",
            ".cpp": "cpp",
            ".cc": "cpp",
            ".h": "c",
            ".hpp": "cpp",
            ".go": "go",
            ".rs": "rust",
            ".java": "java",
            ".rb": "ruby",
            ".php": "php",
            ".cs": "csharp",
            ".swift": "swift",
            ".kt": "kotlin",
        }
        return ext_map.get(file_path.suffix.lower(), "python")

    @staticmethod
    def _extract_imports(content: str) -> list[str]:
        """Extract import statements from content.

        Args:
            content: File content

        Returns:
            List of import statements
        """
        imports: list[str] = []
        patterns = [
            r"^import\s+.+$",
            r"^from\s+\S+\s+import\s+.+$",
            r"^#include\s*[<\"].+[>\"]",
        ]

        for line in content.split("\n")[:30]:
            for pattern in patterns:
                if re.match(pattern, line.strip()):
                    imports.append(line.strip())
                    break

        return imports

    @staticmethod
    def _extract_function_name(lines: list[str], target_index: int) -> Optional[str]:
        """Extract function name containing the target line.

        Args:
            lines: File lines
            target_index: Target line index (0-based)

        Returns:
            Function name if found
        """
        function_patterns = [
            r"^\s*(?:async\s+)?def\s+(\w+)",
            r"^\s*(?:public|private|protected)?\s*(?:static)?\s*\w+\s+\w+\s*\(",
            r"^\s*function\s+(\w+)",
            r"^\s*fn\s+(\w+)",
            r"^\s*(\w+)\s*:\s*function\s*\(",
        ]

        for i in range(target_index, -1, -1):
            line = lines[i]
            for pattern in function_patterns:
                match = re.search(pattern, line)
                if match:
                    if match.groups():
                        return match.group(1)
                    return "anonymous"

        return None


SYSTEM_PROMPT = """You are a code review assistant specialized in generating fixes for code issues.

Your task:
1. Analyze the issue and code context
2. Explain the problem briefly
3. Provide the corrected code
4. Suggest alternatives if applicable

Format your response as:
EXPLANATION: <brief explanation>
FIX: <corrected code>
ALTERNATIVES: <alternative solutions or "None">
CONFIDENCE: <confidence score 0.0-1.0>"""


class LLMSuggester:
    """Use LLM to generate fix suggestions for complex issues.

    This class provides LLM-powered fix generation for issues that
    don't have simple rule-based fixes. It uses code context and
    issue details to generate appropriate solutions.

    The suggester can use:
    - Real LLM providers (OpenAI, Anthropic) via SDK adapters
    - Existing LLM infrastructure (LLMManager from infrastructure/llm)
    - Fallback to template-based suggestions when LLM unavailable

    Features:
    - Retry logic with exponential backoff for rate limits
    - Cost tracking and statistics
    - Configurable retry behavior
    """

    def __init__(
        self,
        provider: Optional[LLMProvider] = None,
        llm_manager: Any = None,
        enable_llm: bool = True,
        max_context_lines: int = 20,
        max_retries: int = 3,
        backoff_base: float = 2.0,
    ) -> None:
        """Initialize the LLM suggester.

        Args:
            provider: LLMProvider instance for direct SDK access
            llm_manager: LLMManager instance from infrastructure/llm
            enable_llm: Whether to attempt LLM calls
            max_context_lines: Maximum context lines for prompts
            max_retries: Maximum retry attempts for rate limits
            backoff_base: Base for exponential backoff
        """
        self._provider = provider
        self._llm_manager = llm_manager
        self.enable_llm = enable_llm
        self.max_context_lines = max_context_lines
        self.max_retries = max_retries
        self.backoff_base = backoff_base
        self.stats = LLMSuggestionStats()

        if enable_llm and provider is None and llm_manager is None:
            self._provider = create_llm_provider_from_env()

    @property
    def provider(self) -> Optional[LLMProvider]:
        """Get the LLM provider if configured."""
        return self._provider

    @property
    def stats_summary(self) -> LLMSuggestionStats:
        """Get current statistics."""
        return self.stats

    @property
    def is_llm_enabled(self) -> bool:
        """Check if LLM generation is enabled and available."""
        if not self.enable_llm:
            return False
        if self._provider is not None:
            return self._provider.is_available()
        if self._llm_manager is not None:
            return True
        return False

    async def suggest_fix(
        self,
        finding: Any,
        context: Optional[CodeContext] = None,
    ) -> Optional[LLMFixSuggestion]:
        """Generate fix using LLM with code context.

        Args:
            finding: Finding object with rule_id, message, severity, etc.
            context: Code context for the finding

        Returns:
            LLMFixSuggestion if successful, None otherwise
        """
        if context is None:
            try:
                context = CodeContext.from_file(finding.file, finding.line)
            except Exception as e:
                logger.warning("Failed to build context: %s", e)
                return None

        prompt = self._build_prompt(finding, context)

        if not self.is_llm_enabled:
            return self._template_suggestion(finding, context)

        try:
            if self._provider is not None:
                response = await self._call_provider_with_retry(
                    self._provider, prompt
                )
            else:
                response = await self._call_llm_manager(prompt)
            
            self.stats.record_success(
                tokens=response.tokens_used,
                cost=self._estimate_cost(response)
            )
            return self._parse_llm_response(response, finding, context)
        except RateLimitError:
            logger.warning("Rate limit exceeded after retries, falling back to template")
            self.stats.record_failure()
            return self._template_suggestion(finding, context)
        except ServiceUnavailableError:
            logger.warning("Service unavailable after retries, falling back to template")
            self.stats.record_failure()
            return self._template_suggestion(finding, context)
        except Exception as e:
            logger.warning("LLM call failed: %s, falling back to template", e)
            self.stats.record_failure()
            return self._template_suggestion(finding, context)

    def _estimate_cost(self, response: Any) -> float:
        """Estimate cost for a response.

        Args:
            response: LLMResponse or similar object

        Returns:
            Estimated cost in USD
        """
        provider_name = getattr(self._provider, "provider_name", "openai")
        model = getattr(self._provider, "model", "gpt-4o-mini")
        tokens_used = getattr(response, "tokens_used", 0)
        
        return calculate_cost(model, tokens_used, 0, provider_name)

    async def _call_provider_with_retry(
        self,
        provider: LLMProvider,
        prompt: str,
    ) -> Any:
        """Call LLM provider with retry logic.

        Args:
            provider: LLM provider instance
            prompt: User prompt

        Returns:
            LLMResponse from provider

        Raises:
            RateLimitError: If rate limited after all retries
            ServiceUnavailableError: If service unavailable after retries
        """
        last_error: Exception | None = None

        for attempt in range(self.max_retries):
            try:
                return await provider.generate(
                    prompt=prompt,
                    system_prompt=SYSTEM_PROMPT,
                    temperature=0.3,
                    max_tokens=2048,
                )
            except RateLimitError:
                wait_time = self.backoff_base ** attempt
                logger.warning(
                    "Rate limit hit on attempt %d/%d, waiting %.1fs",
                    attempt + 1, self.max_retries, wait_time
                )
                await asyncio.sleep(wait_time)
                last_error = RateLimitError()
            except ServiceUnavailableError:
                wait_time = self.backoff_base ** attempt
                logger.warning(
                    "Service unavailable on attempt %d/%d, waiting %.1fs",
                    attempt + 1, self.max_retries, wait_time
                )
                await asyncio.sleep(wait_time)
                last_error = ServiceUnavailableError()
            except Exception as e:
                logger.error("Unexpected error during LLM call: %s", e)
                last_error = e
                break

        if isinstance(last_error, RateLimitError):
            raise RateLimitError()
        if isinstance(last_error, ServiceUnavailableError):
            raise ServiceUnavailableError()
        if last_error:
            raise last_error
        raise RuntimeError("LLM call failed after all retries")

    async def _call_provider(self, provider: LLMProvider, prompt: str) -> str:
        """Call LLM provider directly using SDK adapter."""
        response = await provider.generate(
            prompt=prompt,
            system_prompt=SYSTEM_PROMPT,
            temperature=0.3,
            max_tokens=2048,
        )
        return response.content

    async def _call_llm_manager(self, prompt: str) -> str:
        """Call existing LLMManager infrastructure."""
        if self._llm_manager is None:
            raise ValueError("No LLM manager configured")

        response = await self._llm_manager.generate(
            prompt=prompt,
            system=SYSTEM_PROMPT,
            temperature=0.3,
            max_tokens=2048,
        )
        return response.content

    async def batch_suggest(
        self,
        findings: list[Any],
        contexts: dict[str, CodeContext],
    ) -> dict[str, LLMFixSuggestion]:
        """Generate fixes for multiple findings.

        Args:
            findings: List of findings to generate fixes for
            contexts: Dict mapping file paths to CodeContext

        Returns:
            Dict mapping finding rule_id+file+line to suggestions
        """
        suggestions: dict[str, LLMFixSuggestion] = {}

        for finding in findings:
            key = f"{finding.rule_id}:{finding.file}:{finding.line}"
            context = contexts.get(finding.file)

            suggestion = await self.suggest_fix(finding, context)
            if suggestion:
                suggestions[key] = suggestion

        return suggestions

    def _build_prompt(self, finding: Any, context: CodeContext) -> str:
        """Build prompt for LLM fix generation.

        Args:
            finding: Finding to generate fix for
            context: Code context

        Returns:
            Formatted prompt string
        """
        original_code = context.get_relevant_code(
            finding.line, self.max_context_lines // 2
        )

        if not original_code:
            original_code = "Code unavailable"

        surrounding_code = context.get_surrounding_code(self.max_context_lines)

        return FIX_PROMPT_TEMPLATE.format(
            rule_id=finding.rule_id,
            severity=getattr(finding.severity, "value", finding.severity),
            message=finding.message,
            file_path=finding.file,
            line=finding.line,
            original_code=original_code,
            surrounding_code=surrounding_code,
            language=context.language,
        )

    async def _call_llm(self, prompt: str) -> str:
        """Call LLM with prompt (legacy compatibility)."""
        if self._provider is not None:
            return await self._call_provider(self._provider, prompt)
        if self._llm_manager is not None:
            return await self._call_llm_manager(prompt)
        raise ValueError("No LLM provider configured")

    def _parse_llm_response(
        self,
        response: Any,
        finding: Any,
        context: CodeContext,
    ) -> LLMFixSuggestion:
        """Parse LLM response into structured suggestion.

        Args:
            response: LLMResponse object or raw string
            finding: Original finding
            context: Code context

        Returns:
            LLMFixSuggestion
        """
        content = getattr(response, "content", str(response))
        explanation = ""
        suggested_code = ""
        alternatives: list[str] = []
        confidence = 0.8

        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("EXPLANATION:"):
                explanation = line[12:].strip()
            elif line.startswith("FIX:"):
                suggested_code = line[5:].strip()
            elif line.startswith("ALTERNATIVES:"):
                alt_text = line[13:].strip()
                if alt_text.lower() != "none":
                    alternatives = [a.strip() for a in alt_text.split(";") if a.strip()]
            elif line.startswith("CONFIDENCE:"):
                try:
                    confidence = float(line[11:].strip())
                except ValueError:
                    confidence = 0.8

        if not suggested_code:
            suggested_code = context.get_relevant_code(
                finding.line, self.max_context_lines // 2
            )

        return LLMFixSuggestion(
            original_code=context.get_relevant_code(finding.line),
            suggested_code=suggested_code,
            explanation=explanation or "No explanation provided",
            confidence=confidence,
            alternative_suggestions=alternatives,
            rule_id=finding.rule_id,
        )

    def _template_suggestion(
        self,
        finding: Any,
        context: CodeContext,
    ) -> LLMFixSuggestion:
        """Generate a template-based suggestion when LLM is unavailable.

        Args:
            finding: Finding to generate fix for
            context: Code context

        Returns:
            LLMFixSuggestion with placeholder content
        """
        original_code = context.get_relevant_code(finding.line)

        return LLMFixSuggestion(
            original_code=original_code,
            suggested_code=f"-- Fix for {finding.rule_id} --\n{original_code}",
            explanation=(
                f"LLM provider not configured. Template-based suggestion for "
                f"{finding.rule_id}: {finding.message}"
            ),
            confidence=0.3,
            rule_id=finding.rule_id,
        )

    def _generate_mock_suggestion(
        self,
        finding: Any,
        context: CodeContext,
    ) -> LLMFixSuggestion:
        """Alias for _template_suggestion for backwards compatibility."""
        return self._template_suggestion(finding, context)


def create_llm_suggester(llm_config: Optional[dict[str, Any]] = None) -> LLMSuggester:
    """Create an LLM suggester with configuration.

    Args:
        llm_config: Configuration dict with keys:
            - provider: "openai", "anthropic", or "auto" (default)
            - api_key: Optional API key override
            - model: Optional model override
            - enable_llm: Whether to enable LLM (default True)

    Returns:
        Configured LLMSuggester instance
    """
    provider = None
    enable_llm = True

    if llm_config:
        enable_llm = llm_config.get("enable_llm", True)
        provider_type = llm_config.get("provider", "auto")

        if provider_type != "auto" and provider_type is not None:
            try:
                provider = create_llm_provider(
                    provider=provider_type,
                    api_key=llm_config.get("api_key"),
                    model=llm_config.get("model"),
                )
            except ValueError as e:
                logger.warning("Failed to create provider: %s", e)

    if provider is None and enable_llm:
        provider = create_llm_provider_from_env()

    llm_manager = None
    if llm_config and "llm_manager" in llm_config:
        llm_manager = llm_config["llm_manager"]

    return LLMSuggester(
        provider=provider,
        llm_manager=llm_manager,
        enable_llm=enable_llm,
    )
