"""LLM-based fix suggestion for complex issues.

This module provides LLM-powered fix generation for issues that don't have
rule-based fixes, using code context to generate appropriate solutions.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


FIX_PROMPT_TEMPLATE = """You are a code review assistant. Generate a fix for the following issue.

**Issue:**
- Rule: {rule_id}
- Severity: {severity}
- Message: {message}

**Code Location:**
{file_path}:{line}

**Original Code:**
```{language}
{original_code}
```

**Surrounding Context:**
```{language}
{surrounding_code}
```

**Task:**
1. Explain the issue briefly
2. Provide the corrected code
3. Provide alternative solutions if applicable

Format your response as:
EXPLANATION: <brief explanation>
FIX: <corrected code>
ALTERNATIVES: <alternative solutions or "None">
CONFIDENCE: <confidence score 0.0-1.0>
"""


@dataclass
class LLMFixSuggestion:
    """Fix suggestion generated by LLM.

    Attributes:
        original_code: The original problematic code
        suggested_code: The LLM-generated fix
        explanation: Explanation of the fix
        confidence: Confidence score (0.0-1.0)
        alternative_suggestions: Alternative solutions if available
        rule_id: Associated rule ID
    """
    original_code: str
    suggested_code: str
    explanation: str
    confidence: float = 0.8
    alternative_suggestions: list[str] = field(default_factory=list)
    rule_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "original_code": self.original_code,
            "suggested_code": self.suggested_code,
            "explanation": self.explanation,
            "confidence": self.confidence,
            "alternatives": self.alternative_suggestions,
            "rule_id": self.rule_id,
        }


@dataclass
class CodeContext:
    """Context for LLM fix generation.

    Attributes:
        file_path: Path to the source file
        function_name: Name of containing function (if known)
        surrounding_lines: Lines around the issue
        imports: Import statements in the file
        language: Programming language
    """
    file_path: str
    function_name: Optional[str] = None
    surrounding_lines: list[str] = field(default_factory=list)
    imports: list[str] = field(default_factory=list)
    language: str = "python"

    def get_relevant_code(self, target_line: int, context_lines: int = 3) -> str:
        """Get code around the target line.

        Args:
            target_line: Target line number (1-based)
            context_lines: Number of context lines to include

        Returns:
            Relevant code as string
        """
        if not self.surrounding_lines:
            return ""

        start = max(0, target_line - context_lines - 1)
        end = min(len(self.surrounding_lines), target_line + context_lines)
        return "\n".join(self.surrounding_lines[start:end])

    def get_surrounding_code(self, max_lines: int = 20) -> str:
        """Get surrounding context.

        Args:
            max_lines: Maximum lines to return

        Returns:
            Surrounding code as string
        """
        if not self.surrounding_lines:
            return ""

        lines = self.surrounding_lines[:max_lines]
        return "\n".join(lines)

    @classmethod
    def from_file(
        cls,
        file_path: str | Path,
        target_line: Optional[int] = None,
        context_lines: int = 10,
    ) -> "CodeContext":
        """Create CodeContext from a file.

        Args:
            file_path: Path to the source file
            target_line: Target line to focus on
            context_lines: Lines of context to include

        Returns:
            CodeContext instance
        """
        file_path = Path(file_path)

        try:
            content = file_path.read_text(encoding="utf-8", errors="replace")
            lines = content.split("\n")
        except OSError:
            return cls(file_path=str(file_path), language="python")

        language = cls._detect_language(file_path)
        imports = cls._extract_imports(content)

        if target_line:
            start = max(0, target_line - context_lines - 1)
            end = min(len(lines), target_line + context_lines)
            surrounding = lines[start:end]
            function_name = cls._extract_function_name(lines, target_line - 1)
        else:
            surrounding = lines[:50]
            function_name = None

        return cls(
            file_path=str(file_path),
            function_name=function_name,
            surrounding_lines=surrounding,
            imports=imports,
            language=language,
        )

    @staticmethod
    def _detect_language(file_path: Path) -> str:
        """Detect programming language from file extension."""
        ext_map = {
            ".py": "python",
            ".js": "javascript",
            ".ts": "typescript",
            ".jsx": "javascript",
            ".tsx": "typescript",
            ".c": "c",
            ".cpp": "cpp",
            ".cc": "cpp",
            ".h": "c",
            ".hpp": "cpp",
            ".go": "go",
            ".rs": "rust",
            ".java": "java",
            ".rb": "ruby",
            ".php": "php",
            ".cs": "csharp",
            ".swift": "swift",
            ".kt": "kotlin",
        }
        return ext_map.get(file_path.suffix.lower(), "python")

    @staticmethod
    def _extract_imports(content: str) -> list[str]:
        """Extract import statements from content.

        Args:
            content: File content

        Returns:
            List of import statements
        """
        imports: list[str] = []
        patterns = [
            r"^import\s+.+$",
            r"^from\s+\S+\s+import\s+.+$",
            r"^#include\s*[<\"].+[>\"]",
        ]

        for line in content.split("\n")[:30]:
            for pattern in patterns:
                if re.match(pattern, line.strip()):
                    imports.append(line.strip())
                    break

        return imports

    @staticmethod
    def _extract_function_name(lines: list[str], target_index: int) -> Optional[str]:
        """Extract function name containing the target line.

        Args:
            lines: File lines
            target_index: Target line index (0-based)

        Returns:
            Function name if found
        """
        function_patterns = [
            r"^\s*(?:async\s+)?def\s+(\w+)",
            r"^\s*(?:public|private|protected)?\s*(?:static)?\s*\w+\s+\w+\s*\(",
            r"^\s*function\s+(\w+)",
            r"^\s*fn\s+(\w+)",
            r"^\s*(\w+)\s*:\s*function\s*\(",
        ]

        for i in range(target_index, -1, -1):
            line = lines[i]
            for pattern in function_patterns:
                match = re.search(pattern, line)
                if match:
                    if match.groups():
                        return match.group(1)
                    return "anonymous"

        return None


class LLMSuggester:
    """Use LLM to generate fix suggestions for complex issues.

    This class provides LLM-powered fix generation for issues that
    don't have simple rule-based fixes. It uses code context and
    issue details to generate appropriate solutions.
    """

    def __init__(
        self,
        llm_provider: Any = None,
        max_context_lines: int = 20,
    ) -> None:
        """Initialize the LLM suggester.

        Args:
            llm_provider: LLM provider/gateway for API calls
            max_context_lines: Maximum context lines for prompts
        """
        self.llm_provider = llm_provider
        self.max_context_lines = max_context_lines

    async def suggest_fix(
        self,
        finding: Any,
        context: Optional[CodeContext] = None,
    ) -> Optional[LLMFixSuggestion]:
        """Generate fix using LLM with code context.

        Args:
            finding: Finding object with rule_id, message, severity, etc.
            context: Code context for the finding

        Returns:
            LLMFixSuggestion if successful, None otherwise
        """
        if context is None:
            try:
                context = CodeContext.from_file(finding.file, finding.line)
            except Exception as e:
                logger.warning("Failed to build context: %s", e)
                return None

        prompt = self._build_prompt(finding, context)

        if self.llm_provider is None:
            return self._generate_mock_suggestion(finding, context)

        try:
            response = await self._call_llm(prompt)
            return self._parse_llm_response(response, finding, context)
        except Exception as e:
            logger.error("LLM fix generation failed: %s", e)
            return self._generate_mock_suggestion(finding, context)

    async def batch_suggest(
        self,
        findings: list[Any],
        contexts: dict[str, CodeContext],
    ) -> dict[str, LLMFixSuggestion]:
        """Generate fixes for multiple findings.

        Args:
            findings: List of findings to generate fixes for
            contexts: Dict mapping file paths to CodeContext

        Returns:
            Dict mapping finding rule_id+file+line to suggestions
        """
        suggestions: dict[str, LLMFixSuggestion] = {}

        for finding in findings:
            key = f"{finding.rule_id}:{finding.file}:{finding.line}"
            context = contexts.get(finding.file)

            suggestion = await self.suggest_fix(finding, context)
            if suggestion:
                suggestions[key] = suggestion

        return suggestions

    def _build_prompt(self, finding: Any, context: CodeContext) -> str:
        """Build prompt for LLM fix generation.

        Args:
            finding: Finding to generate fix for
            context: Code context

        Returns:
            Formatted prompt string
        """
        original_code = context.get_relevant_code(
            finding.line, self.max_context_lines // 2
        )

        if not original_code:
            original_code = "Code unavailable"

        surrounding_code = context.get_surrounding_code(self.max_context_lines)

        return FIX_PROMPT_TEMPLATE.format(
            rule_id=finding.rule_id,
            severity=getattr(finding.severity, "value", finding.severity),
            message=finding.message,
            file_path=finding.file,
            line=finding.line,
            original_code=original_code,
            surrounding_code=surrounding_code,
            language=context.language,
        )

    async def _call_llm(self, prompt: str) -> str:
        """Call LLM with prompt.

        Args:
            prompt: The prompt to send

        Returns:
            LLM response text
        """
        if self.llm_provider is None:
            raise ValueError("No LLM provider configured")

        response = await self.llm_provider.complete(
            prompt=prompt,
            max_tokens=1000,
            temperature=0.3,
        )

        return response

    def _parse_llm_response(
        self,
        response: str,
        finding: Any,
        context: CodeContext,
    ) -> LLMFixSuggestion:
        """Parse LLM response into structured suggestion.

        Args:
            response: Raw LLM response
            finding: Original finding
            context: Code context

        Returns:
            LLMFixSuggestion
        """
        explanation = ""
        suggested_code = ""
        alternatives: list[str] = []
        confidence = 0.8

        for line in response.split("\n"):
            line = line.strip()
            if line.startswith("EXPLANATION:"):
                explanation = line[12:].strip()
            elif line.startswith("FIX:"):
                suggested_code = line[5:].strip()
            elif line.startswith("ALTERNATIVES:"):
                alt_text = line[13:].strip()
                if alt_text.lower() != "none":
                    alternatives = [a.strip() for a in alt_text.split(";") if a.strip()]
            elif line.startswith("CONFIDENCE:"):
                try:
                    confidence = float(line[11:].strip())
                except ValueError:
                    confidence = 0.8

        if not suggested_code:
            suggested_code = context.get_relevant_code(
                finding.line, self.max_context_lines // 2
            )

        return LLMFixSuggestion(
            original_code=context.get_relevant_code(finding.line),
            suggested_code=suggested_code,
            explanation=explanation or "No explanation provided",
            confidence=confidence,
            alternative_suggestions=alternatives,
            rule_id=finding.rule_id,
        )

    def _generate_mock_suggestion(
        self,
        finding: Any,
        context: CodeContext,
    ) -> LLMFixSuggestion:
        """Generate a mock suggestion when LLM is unavailable.

        Args:
            finding: Finding to generate fix for
            context: Code context

        Returns:
            LLMFixSuggestion with placeholder content
        """
        original_code = context.get_relevant_code(finding.line)

        return LLMFixSuggestion(
            original_code=original_code,
            suggested_code=f"-- LLM fix for {finding.rule_id} --\n{original_code}",
            explanation=(
                f"LLM provider not configured. Manual fix required for "
                f"{finding.rule_id}: {finding.message}"
            ),
            confidence=0.0,
            rule_id=finding.rule_id,
        )


def create_llm_suggester(llm_config: Optional[dict[str, Any]] = None) -> LLMSuggester:
    """Create an LLM suggester with configuration.

    Args:
        llm_config: LLM provider configuration

    Returns:
        Configured LLMSuggester instance
    """
    llm_provider = None

    if llm_config:
        try:
            from src.infrastructure.llm.gateway import LLMGateway
            llm_provider = LLMGateway(config=llm_config)
        except ImportError:
            logger.warning("LLM gateway not available")

    return LLMSuggester(llm_provider=llm_provider)
