"""LLM-powered fix generation for complex issues.

This module provides LLM-powered fix generation for issues that require
complex understanding beyond template-based fixes.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class FixSuggestion:
    """A fix suggestion generated by LLM."""
    fix_code: str
    explanation: str
    confidence: float
    tests_needed: List[str] = field(default_factory=list)
    alternative_fixes: List[str] = field(default_factory=list)


class LLMFixGenerator:
    """Generate contextual fixes using LLM.

    This module provides LLM-powered fix generation for issues that
    require complex understanding beyond template-based fixes.
    """

    DEFAULT_MODEL = "gpt-4"
    TEMPERATURE = 0.3

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
    ):
        """Initialize LLM fix generator.

        Args:
            api_key: OpenAI API key (or set OPENAI_API_KEY env var)
            model: Model to use (default: gpt-4)
        """
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.model = model or self.DEFAULT_MODEL
        self._client = None

        if self.api_key:
            self._init_client()

    def _init_client(self) -> None:
        """Initialize OpenAI client."""
        try:
            from openai import AsyncOpenAI
            self._client = AsyncOpenAI(api_key=self.api_key)
            logger.info("LLM client initialized with model: %s", self.model)
        except ImportError:
            logger.warning("openai package not installed. LLM fixes disabled.")

    async def generate_fix(
        self,
        finding: Dict[str, Any],
        context: Dict[str, Any],
    ) -> Optional[FixSuggestion]:
        """Generate a contextual fix using LLM.

        Args:
            finding: Finding information (rule_id, message, file, line, etc.)
            context: Code context (content, language, surrounding lines, etc.)

        Returns:
            FixSuggestion with generated code, or None if generation failed
        """
        if not self._client:
            logger.warning("LLM client not available")
            return None

        prompt = self._build_prompt(finding, context)

        try:
            response = await self._client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": self._get_system_prompt()
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=self.TEMPERATURE,
                max_tokens=1000,
            )

            content = response.choices[0].message.content
            return self._parse_response(content)

        except Exception as e:
            logger.error("LLM fix generation failed: %s", e)
            return None

    def _build_prompt(self, finding: Dict, context: Dict) -> str:
        """Build prompt for fix generation.

        Args:
            finding: Finding data
            context: Context data

        Returns:
            Formatted prompt string
        """
        file_path = finding.get('file', 'unknown')
        line = finding.get('line', 0)
        rule_id = finding.get('rule_id', 'UNKNOWN')
        message = finding.get('message', '')
        severity = finding.get('severity', 'UNKNOWN')

        language = context.get('language', 'python')
        surrounding = context.get('surrounding', '')

        return f"""You are an expert code reviewer. Generate a fix for this issue.

FILE: {file_path}
LINE: {line}
RULE: {rule_id}
ISSUE: {message}
SEVERITY: {severity}

CODE CONTEXT:
```{language}
{surrounding}
```

REQUIREMENTS:
1. Fix the root cause, not just symptoms
2. Maintain code style consistency with the surrounding code
3. Ensure the fix is minimal and focused
4. Consider edge cases and error handling
5. If multiple approaches are valid, suggest the best one

Respond ONLY with valid JSON in this format:
{{
    "fix_code": "the corrected code snippet",
    "explanation": "brief explanation of the fix",
    "confidence": 0.0-1.0,
    "tests_needed": ["test description 1", "test description 2"],
    "alternative_fixes": ["alternative approach 1"]
}}

IMPORTANT: Return ONLY the JSON, no other text."""

    def _get_system_prompt(self) -> str:
        """Get system prompt for fix generation."""
        return """You are an expert software engineer specializing in code review and bug fixing.

Your role is to:
1. Understand the root cause of issues
2. Generate minimal, focused fixes
3. Explain why the fix works
4. Suggest tests to prevent regression

Guidelines:
- Prioritize security and correctness
- Maintain code style and patterns
- Don't over-engineer solutions
- Consider performance implications
- Follow language best practices"""

    def _parse_response(self, content: str) -> Optional[FixSuggestion]:
        """Parse LLM response into FixSuggestion.

        Args:
            content: Raw response content

        Returns:
            Parsed FixSuggestion or None
        """
        try:
            # Extract JSON from response
            content = content.strip()

            # Handle markdown code blocks
            if content.startswith('```'):
                lines = content.split('\n')
                content = '\n'.join(lines[1:-1])

            # Parse JSON
            data = json.loads(content)

            return FixSuggestion(
                fix_code=data.get('fix_code', ''),
                explanation=data.get('explanation', ''),
                confidence=float(data.get('confidence', 0.5)),
                tests_needed=data.get('tests_needed', []),
                alternative_fixes=data.get('alternative_fixes', []),
            )

        except json.JSONDecodeError as e:
            logger.error("Failed to parse LLM response: %s", e)
            logger.debug("Raw response: %s", content[:500])
            return None

    def is_available(self) -> bool:
        """Check if LLM is available.

        Returns:
            True if LLM client is initialized
        """
        return self._client is not None


class LocalLLMFixer:
    """Fallback LLM fixer using local models (Ollama, LM Studio, etc.)."""

    def __init__(self, base_url: str = "http://localhost:11434"):
        """Initialize local LLM fixer.

        Args:
            base_url: Base URL for local LLM API (default: Ollama)
        """
        self.base_url = base_url.rstrip('/')
        self._client = None
        self._init_client()

    def _init_client(self) -> None:
        """Initialize HTTP client for local LLM."""
        try:
            import aiohttp
            self._client = aiohttp.ClientSession()
            logger.info("Local LLM client initialized: %s", self.base_url)
        except ImportError:
            logger.warning("aiohttp not installed. Local LLM disabled.")

    async def generate_fix(
        self,
        finding: Dict,
        context: Dict,
    ) -> Optional[FixSuggestion]:
        """Generate fix using local LLM.

        Args:
            finding: Finding data
            context: Context data

        Returns:
            FixSuggestion or None
        """
        if not self._client:
            return None

        prompt = self._build_prompt(finding, context)

        try:
            import aiohttp
            async with self._client.post(
                f"{self.base_url}/api/generate",
                json={
                    "model": "codellama",
                    "prompt": prompt,
                    "stream": False,
                },
                timeout=aiohttp.ClientTimeout(total=30),
            ) as response:
                if response.status == 200:
                    data = await response.json()
                    content = data.get('response', '')
                    return self._parse_response(content)

        except Exception as e:
            logger.error("Local LLM fix generation failed: %s", e)

        return None

    def _build_prompt(self, finding: Dict, context: Dict) -> str:
        """Build prompt for local LLM."""
        file_path = finding.get('file', 'unknown')
        message = finding.get('message', '')
        language = context.get('language', 'python')
        code = context.get('surrounding', '')

        return f"""Fix this code issue:

File: {file_path}
Issue: {message}

Code:
```{language}
{code}
```

Provide a fix in JSON format with fix_code, explanation, confidence, and tests_needed."""

    def _parse_response(self, content: str) -> Optional[FixSuggestion]:
        """Parse local LLM response."""
        try:
            # Try to find JSON in response
            start = content.find('{')
            end = content.rfind('}') + 1

            if start >= 0 and end > start:
                data = json.loads(content[start:end])
                return FixSuggestion(
                    fix_code=data.get('fix_code', content),
                    explanation=data.get('explanation', 'Generated by local LLM'),
                    confidence=data.get('confidence', 0.6),
                    tests_needed=data.get('tests_needed', []),
                    alternative_fixes=data.get('alternative_fixes', []),
                )
            else:
                return FixSuggestion(
                    fix_code=content.strip(),
                    explanation="Generated by local LLM",
                    confidence=0.6,
                    tests_needed=[],
                    alternative_fixes=[],
                )
        except (json.JSONDecodeError, ValueError):
            return FixSuggestion(
                fix_code=content.strip(),
                explanation="Generated by local LLM",
                confidence=0.5,
                tests_needed=[],
                alternative_fixes=[],
            )
