"""Analysis rules package."""

from .security import (
    SQLInjectionRule,
    HardcodedSecretRule,
    CommandInjectionRule,
    XSSRule,
    PathTraversalRule,
    InsecureHashRule,
    InsecureRandomRule,
    UnsafeDeserializationRule,
    WeakCryptoRule,
    UnsafeYAMLRule,
    XXERule,
    LDAPInjectionRule,
    DeserializationBypassRule,
    HardcodedCredentialsRule,
    SSLVerificationRule,
    CookieSecurityRule,
    CSRFRule,
    IDORRule,
    RaceConditionRule,
    UnsafeRedirectRule,
    WeakHashRule,
    UnsafePickleRule,
    HardcodedIVRule,
    InsecureTempFileRule,
    UnsafeYAMLLoadRule,
    AssertStatementRule,
)
from .quality import (
    CognitiveComplexityRule,
    EmptyExceptRule,
    BroadExceptRule,
    GlobalVariableRule,
    CommentedCodeRule,
    DeprecatedImportRule,
    MissingFinallyRule,
    SwallowedExceptionRule,
    RaiseGenericRule,
    NestedTryRule,
    SuccessWithoutReturnRule,
)
from .imports import (
    UnusedImportRule,
    CircularImportRule,
)
from .types import (
    AnyTypeRule,
)
from .naming import (
    InconsistentNamingRule,
)
from .performance import (
    InefficientStringConcatRule,
    NPlusOneRule,
    InefficientListRule,
    RecursiveWithoutMemoRule,
    InefficientComprehensionRule,
    RegexInLoopRule,
    DuplicateQueriesRule,
    SyncInAsyncRule,
    UnnecessaryAllRule,
    LazyVsEagerRule,
    UnnecessaryConversionRule,
    InefficientDictRule,
    GlobVsListdirRule,
    YieldVsReturnRule,
    InefficientSetOpsRule,
)
from .testing import (
    MissingAssertionsRule,
    SlowTestRule,
    HardcodedInTestRule,
    EmptyTestRule,
    SharedStateRule,
    FlakyTestRule,
    MissingMockRule,
    TestOrderDependencyRule,
    OverlyBroadMockRule,
    MissingCleanupRule,
)
from .documentation import (
    MissingDocstringRule,
    OutdatedDocstringRule,
    MissingTypeHintsRule,
    BrokenLinkRule,
    MissingExampleRule,
)

__all__ = [
    # Security (SEC001-SEC027)
    "SQLInjectionRule",
    "HardcodedSecretRule",
    "CommandInjectionRule",
    "XSSRule",
    "PathTraversalRule",
    "InsecureHashRule",
    "InsecureRandomRule",
    "UnsafeDeserializationRule",
    "WeakCryptoRule",
    "UnsafeYAMLRule",
    "XXERule",
    "LDAPInjectionRule",
    "DeserializationBypassRule",
    "HardcodedCredentialsRule",
    "SSLVerificationRule",
    "CookieSecurityRule",
    "CSRFRule",
    "IDORRule",
    "RaceConditionRule",
    "UnsafeRedirectRule",
    "WeakHashRule",
    "UnsafePickleRule",
    "HardcodedIVRule",
    "InsecureTempFileRule",
    "UnsafeYAMLLoadRule",
    "AssertStatementRule",
    # Quality (QUAL001-QUAL015)
    "CognitiveComplexityRule",
    "EmptyExceptRule",
    "BroadExceptRule",
    "GlobalVariableRule",
    "CommentedCodeRule",
    "DeprecatedImportRule",
    "MissingFinallyRule",
    "SwallowedExceptionRule",
    "RaiseGenericRule",
    "NestedTryRule",
    "SuccessWithoutReturnRule",
    # Imports (IMP001-IMP004)
    "UnusedImportRule",
    "CircularImportRule",
    # Types (TYPE001)
    "AnyTypeRule",
    # Naming (NAME001)
    "InconsistentNamingRule",
    # Performance (PERF001-PERF015)
    "InefficientStringConcatRule",
    "NPlusOneRule",
    "InefficientListRule",
    "RecursiveWithoutMemoRule",
    "InefficientComprehensionRule",
    "RegexInLoopRule",
    "DuplicateQueriesRule",
    "SyncInAsyncRule",
    "UnnecessaryAllRule",
    "LazyVsEagerRule",
    "UnnecessaryConversionRule",
    "InefficientDictRule",
    "GlobVsListdirRule",
    "YieldVsReturnRule",
    "InefficientSetOpsRule",
    # Testing (TEST001-TEST010)
    "MissingAssertionsRule",
    "SlowTestRule",
    "HardcodedInTestRule",
    "EmptyTestRule",
    "SharedStateRule",
    "FlakyTestRule",
    "MissingMockRule",
    "TestOrderDependencyRule",
    "OverlyBroadMockRule",
    "MissingCleanupRule",
    # Documentation (DOC001-DOC005)
    "MissingDocstringRule",
    "OutdatedDocstringRule",
    "MissingTypeHintsRule",
    "BrokenLinkRule",
    "MissingExampleRule",
]
