"""Self-reflection module for agent improvement and error recovery.

Monitors execution results, detects failure patterns, and generates
corrective actions to improve future reasoning.

Architecture:
    Result → ReflectionEngine → FailureDetector → CorrectionGenerator → ImprovedResult
                ↓
         PatternLearner → LearnedPatterns → Future reasoning
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional

import structlog

logger = structlog.get_logger(__name__)


class FailurePattern(Enum):
    """Categories of failure patterns detected by reflection."""
    HARDWARE_CONSTRAINT = "hardware_constraint"
    INITIALIZATION_ORDER = "initialization_order"
    RESOURCE_CONFLICT = "resource_conflict"
    TIMING_VIOLATION = "timing_violation"
    REGISTER_ACCESS = "register_access"
    INTERRUPT_MISCONFIG = "interrupt_misconfig"
    CLOCK_MISCONFIG = "clock_misconfig"
    PIN_ASSIGNMENT = "pin_assignment"
    DMA_CONFLICT = "dma_conflict"
    MEMORY_ALLOCATION = "memory_allocation"
    VALIDATION_SKIP = "validation_skip"
    UNKNOWN = "unknown"


class CorrectionStrategy(Enum):
    """Strategy to apply for correction."""
    ADD_VALIDATION = "add_validation"
    REORDER_STEPS = "reorder_steps"
    CONSTRAINT_INJECTION = "constraint_injection"
    ESCALATE_TO_HARDWARE_KB = "escalate_to_hardware_kb"
    REQUEST_MORE_CONTEXT = "request_more_context"
    RETRY_WITH_DIFFERENT_APPROACH = "retry_different_approach"
    DECOMPOSE_TASK = "decompose_task"
    NO_OP = "no_op"


@dataclass
class FailureInstance:
    """A detected failure instance."""
    pattern: FailurePattern
    description: str
    location: str | None
    timestamp: datetime
    severity: str  # "error", "warning", "info"
    raw_error: str
    context: dict[str, Any] = field(default_factory=dict)


@dataclass
class Correction:
    """A corrective action generated by reflection."""
    strategy: CorrectionStrategy
    description: str
    target_step: int | None
    constraints_to_add: list[str] = field(default_factory=list)
    steps_to_reorder: list[tuple[int, int]] = field(default_factory=list)  # (from, to)
    new_steps: list[dict[str, Any]] = field(default_factory=list)
    escalate: bool = False
    escalation_reason: str | None = None


@dataclass
class LearnedPattern:
    """A pattern learned from past failures."""
    pattern: FailurePattern
    symptom_signature: str      # Hash of error message pattern
    correction_strategy: CorrectionStrategy
    occurrence_count: int
    success_rate: float
    last_applied: datetime
    example_errors: list[str] = field(default_factory=list)


@dataclass
class ReflectionResult:
    """Output of the reflection process."""
    original_result: dict[str, Any]
    failures: list[FailureInstance]
    corrections: list[Correction]
    learned_patterns_applied: list[LearnedPattern]
    improvements: list[str]
    escalation_required: bool
    escalation_reasons: list[str]
    overall_assessment: str
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "failures": [
                {"pattern": f.pattern.value, "description": f.description, "severity": f.severity}
                for f in self.failures
            ],
            "corrections": [
                {"strategy": c.strategy.value, "description": c.description}
                for c in self.corrections
            ],
            "improvements": self.improvements,
            "escalation_required": self.escalation_required,
            "assessment": self.overall_assessment,
        }


class Reflection:
    """
    Self-reflection engine for AI_SUPPORT.

    Monitors execution results, detects patterns of failure, generates
    corrections, and learns from past experiences.

    Usage:
        reflection = Reflection()

        # After a reasoning/plan execution
        result = await reflection.reflect({
            "success": False,
            "errors": ["CLOCK_003: Clock not enabled for SPI1"],
            "steps": [...],
        })

        # Apply corrections
        improved_plan = reflection.apply_corrections(original_plan, result.corrections)
    """

    def __init__(
        self,
        max_learned_patterns: int = 100,
        confidence_threshold: float = 0.8,
        escalation_error_threshold: int = 3,
    ):
        self.max_learned_patterns = max_learned_patterns
        self.confidence_threshold = confidence_threshold
        self.escalation_error_threshold = escalation_error_threshold

        self._learned_patterns: dict[str, LearnedPattern] = {}
        self._failure_history: list[FailureInstance] = []
        self._reflection_count = 0

    async def reflect(
        self,
        result: dict[str, Any],
        feedback: dict[str, Any] | None = None,
    ) -> ReflectionResult:
        """
        Reflect on execution result and generate corrections.

        Args:
            result: Execution result with keys:
                - success: bool
                - errors: list[str]
                - warnings: list[str]
                - steps: list of reasoning/plan steps
                - confidence: float
                - context: dict with task info
            feedback: Optional external feedback dict

        Returns:
            ReflectionResult with failures, corrections, and improvements
        """
        self._reflection_count += 1
        logger.info(
            "reflection_start",
            reflection_count=self._reflection_count,
            success=result.get("success", False),
        )

        # Step 1: Detect failures
        failures = self._detect_failures(result)

        # Step 2: Classify failure patterns
        classified_failures = self._classify_failures(failures)

        # Step 3: Check learned patterns
        applied_patterns = self._match_learned_patterns(failures)

        # Step 4: Generate corrections
        corrections = self._generate_corrections(
            classified_failures, applied_patterns, feedback
        )

        # Step 5: Learn from this reflection
        self._update_learned_patterns(failures, corrections)

        # Step 6: Determine escalation
        escalation_required, escalation_reasons = self._check_escalation(
            failures, corrections
        )

        # Step 7: Build improvement list
        improvements = self._build_improvements(
            failures, corrections, applied_patterns
        )

        # Step 8: Overall assessment
        assessment = self._assess_result(result, failures, corrections)

        reflection_result = ReflectionResult(
            original_result=result,
            failures=failures,
            corrections=corrections,
            learned_patterns_applied=applied_patterns,
            improvements=improvements,
            escalation_required=escalation_required,
            escalation_reasons=escalation_reasons,
            overall_assessment=assessment,
            metadata={
                "reflection_count": self._reflection_count,
                "patterns_applied": len(applied_patterns),
                "corrections_generated": len(corrections),
            },
        )

        logger.info(
            "reflection_complete",
            failures=len(failures),
            corrections=len(corrections),
            escalation=escalation_required,
            assessment=assessment,
        )

        return reflection_result

    # ─── Step 1: Failure Detection ─────────────────────────────────────

    def _detect_failures(self, result: dict[str, Any]) -> list[FailureInstance]:
        """Detect failures from execution result."""
        failures: list[FailureInstance] = []

        errors = result.get("errors", [])
        warnings = result.get("warnings", [])
        context = result.get("context", {})

        # Extract errors
        for error in errors:
            failure = FailureInstance(
                pattern=FailurePattern.UNKNOWN,
                description=self._extract_error_description(error),
                location=self._extract_error_location(error),
                timestamp=datetime.now(),
                severity="error",
                raw_error=error,
                context=context,
            )
            failures.append(failure)

        # Extract warnings that might indicate problems
        for warning in warnings:
            # Only treat warnings as failures if they match known problem patterns
            if self._is_significant_warning(warning):
                failure = FailureInstance(
                    pattern=FailurePattern.UNKNOWN,
                    description=self._extract_error_description(warning),
                    location=self._extract_error_location(warning),
                    timestamp=datetime.now(),
                    severity="warning",
                    raw_error=warning,
                    context=context,
                )
                failures.append(failure)

        # Check for confidence below threshold
        confidence = result.get("confidence", 1.0)
        if confidence < self.confidence_threshold:
            failures.append(FailureInstance(
                pattern=FailurePattern.VALIDATION_SKIP,
                description=f"Low confidence: {confidence:.2f} < {self.confidence_threshold}",
                location="overall",
                timestamp=datetime.now(),
                severity="warning",
                raw_error=f"confidence={confidence}",
                context={"confidence": confidence},
            ))

        # Check for steps that failed
        steps = result.get("steps", [])
        for i, step in enumerate(steps):
            if isinstance(step, dict):
                if not step.get("validation_result", True):
                    failures.append(FailureInstance(
                        pattern=FailurePattern.UNKNOWN,
                        description=f"Step {i} failed validation",
                        location=f"step_{i}",
                        timestamp=datetime.now(),
                        severity="error",
                        raw_error=step.get("error", "validation_failed"),
                        context={"step_index": i, "step": step},
                    ))

        return failures

    def _extract_error_description(self, error: str) -> str:
        """Extract human-readable error description."""
        # Handle [CODE] format
        if "]" in error:
            return error.split("]", 1)[1].strip()
        return error

    def _extract_error_location(self, error: str) -> str | None:
        """Extract location from error message."""
        if "location=" in error.lower():
            parts = error.split("location=", 1)
            if len(parts) > 1:
                loc = parts[1].split(",")[0].split(")")[0].strip()
                return loc
        return None

    def _is_significant_warning(self, warning: str) -> bool:
        """Determine if a warning indicates a significant problem."""
        significant_keywords = [
            "MISSING", "NOT FOUND", "UNKNOWN", "CONFLICT",
            "MAY NOT SUPPORT", "SPEED LIMIT", "ALREADY ALLOCATED",
        ]
        return any(kw in warning.upper() for kw in significant_keywords)

    # ─── Step 2: Pattern Classification ───────────────────────────────

    def _classify_failures(
        self, failures: list[FailureInstance]
    ) -> list[FailureInstance]:
        """Classify each failure into a specific pattern."""
        classified = []

        for failure in failures:
            classified_pattern = self._classify_single(failure)
            failure.pattern = classified_pattern
            classified.append(failure)

        return classified

    def _classify_single(self, failure: FailureInstance) -> FailurePattern:
        """Classify a single failure into a pattern."""
        error = failure.raw_error.upper()
        desc = failure.description.upper()

        # Hardware constraint violations
        if any(k in error for k in ["CLOCK", "CLK", "ENABLE"]):
            return FailurePattern.CLOCK_MISCONFIG
        if any(k in error for k in ["PIN", "GPIO", "AF", "ALTERNATE"]):
            return FailurePattern.PIN_ASSIGNMENT
        if any(k in error for k in ["IRQ", "INTERRUPT", "NVIC", "PRIORITY"]):
            return FailurePattern.INTERRUPT_MISCONFIG
        if any(k in error for k in ["REGISTER", "ACCESS", "WRITE", "READ"]):
            return FailurePattern.REGISTER_ACCESS
        if any(k in error for k in ["DMA", "CHANNEL", "REQUEST"]):
            return FailurePattern.DMA_CONFLICT
        if any(k in error for k in ["RESERVED", "CONFLICT", "DUPLICATE", "ALREADY"]):
            return FailurePattern.RESOURCE_CONFLICT
        if any(k in error for k in ["TIMING", "DELAY", "LATENCY", "SPEED"]):
            return FailurePattern.TIMING_VIOLATION
        if any(k in error for k in ["ORDER", "DEPENDENCY", "BEFORE"]):
            return FailurePattern.INITIALIZATION_ORDER
        if any(k in error for k in ["MEMORY", "HEAP", "STACK", "ALLOC"]):
            return FailurePattern.MEMORY_ALLOCATION
        if any(k in desc for k in ["VALIDATION", "SKIP", "MISSING CHECK"]):
            return FailurePattern.VALIDATION_SKIP

        # Hardware-related keywords
        if any(k in desc for k in ["PERIPHERAL", "MCU", "RCC", "AHB", "APB"]):
            return FailurePattern.HARDWARE_CONSTRAINT

        return FailurePattern.UNKNOWN

    # ─── Step 3: Learned Pattern Matching ──────────────────────────────

    def _match_learned_patterns(
        self, failures: list[FailureInstance]
    ) -> list[LearnedPattern]:
        """Match current failures against learned patterns."""
        matched: list[LearnedPattern] = []

        for failure in failures:
            signature = self._error_signature(failure.raw_error)
            pattern = self._learned_patterns.get(signature)

            if pattern and pattern.occurrence_count >= 2:
                pattern.last_applied = datetime.now()
                matched.append(pattern)
                logger.debug(
                    "learned_pattern_matched",
                    pattern=pattern.pattern.value,
                    occurrences=pattern.occurrence_count,
                )

        return matched

    def _error_signature(self, error: str) -> str:
        """Generate a signature hash for error matching."""
        import hashlib
        # Normalize error: remove dynamic values (addresses, numbers)
        import re
        normalized = re.sub(r"0x[0-9A-Fa-f]+", "0xADDR", error)
        normalized = re.sub(r"\d+", "N", normalized)
        normalized = normalized.upper()
        return hashlib.md5(normalized.encode()).hexdigest()[:12]

    # ─── Step 4: Correction Generation ────────────────────────────────

    def _generate_corrections(
        self,
        failures: list[FailureInstance],
        matched_patterns: list[LearnedPattern],
        feedback: dict[str, Any] | None,
    ) -> list[Correction]:
        """Generate corrective actions for failures."""
        corrections: list[Correction] = []

        for failure in failures:
            correction = self._correct_single(failure)
            if correction:
                corrections.append(correction)

        # Apply corrections from learned patterns
        for pattern in matched_patterns:
            if pattern.correction_strategy not in [c.strategy for c in corrections]:
                corrections.append(Correction(
                    strategy=pattern.correction_strategy,
                    description=f"Learned correction from pattern: {pattern.pattern.value}",
                    target_step=None,
                ))

        # Apply external feedback corrections
        if feedback:
            fb_correction = self._from_feedback(feedback)
            if fb_correction:
                corrections.append(fb_correction)

        return corrections

    def _correct_single(self, failure: FailureInstance) -> Correction | None:
        """Generate correction for a single failure."""
        pattern = failure.pattern

        if pattern == FailurePattern.CLOCK_MISCONFIG:
            return Correction(
                strategy=CorrectionStrategy.CONSTRAINT_INJECTION,
                description="Add clock enable validation before peripheral access",
                target_step=None,
                constraints_to_add=[
                    "Enable peripheral clock in RCC before any register access",
                    "Verify clock source and prescaler match peripheral requirements",
                ],
            )

        if pattern == FailurePattern.PIN_ASSIGNMENT:
            return Correction(
                strategy=CorrectionStrategy.ADD_VALIDATION,
                description="Add pin routing and alternate function validation",
                target_step=None,
                constraints_to_add=[
                    "Check pin availability and reservation status",
                    "Validate alternate function mapping for peripheral",
                    "Verify pin is not used by another peripheral",
                ],
            )

        if pattern == FailurePattern.INTERRUPT_MISCONFIG:
            return Correction(
                strategy=CorrectionStrategy.ADD_VALIDATION,
                description="Add NVIC priority and IRQ availability validation",
                target_step=None,
                constraints_to_add=[
                    "Check IRQ availability before assignment",
                    "Validate NVIC priority (0-15 for STM32)",
                    "Ensure no priority inversion with existing handlers",
                ],
            )

        if pattern == FailurePattern.REGISTER_ACCESS:
            return Correction(
                strategy=CorrectionStrategy.ADD_VALIDATION,
                description="Add register schema validation before access",
                target_step=None,
                constraints_to_add=[
                    "Verify register exists in peripheral schema",
                    "Check access type compatibility (read/write)",
                    "Validate bitfield boundaries",
                ],
            )

        if pattern == FailurePattern.DMA_CONFLICT:
            return Correction(
                strategy=CorrectionStrategy.CONSTRAINT_INJECTION,
                description="Add DMA channel allocation validation",
                target_step=None,
                constraints_to_add=[
                    "Check DMA channel availability",
                    "Validate DMA request mapping for peripheral",
                    "Ensure no channel conflict with active DMA transfers",
                ],
            )

        if pattern == FailurePattern.INITIALIZATION_ORDER:
            return Correction(
                strategy=CorrectionStrategy.REORDER_STEPS,
                description="Reorder initialization to respect dependencies",
                target_step=None,
            )

        if pattern == FailurePattern.RESOURCE_CONFLICT:
            return Correction(
                strategy=CorrectionStrategy.CONSTRAINT_INJECTION,
                description="Add resource conflict detection",
                target_step=None,
                constraints_to_add=[
                    "Check pin/IRQ/DMA availability before allocation",
                    "Build resource allocation table",
                    "Detect conflicts before code generation",
                ],
            )

        if pattern == FailurePattern.TIMING_VIOLATION:
            return Correction(
                strategy=CorrectionStrategy.ESCALATE_TO_HARDWARE_KB,
                description="Escalate timing analysis to hardware knowledge base",
                target_step=None,
                escalate=True,
                escalation_reason="Timing constraint violation requires detailed clock tree analysis",
            )

        if pattern == FailurePattern.VALIDATION_SKIP:
            return Correction(
                strategy=CorrectionStrategy.ADD_VALIDATION,
                description="Re-run validation with full constraint checking",
                target_step=None,
                constraints_to_add=[
                    "Run HardwareValidator with all rule sets",
                    "Check confidence threshold before proceeding",
                ],
            )

        if pattern == FailurePattern.HARDWARE_CONSTRAINT:
            return Correction(
                strategy=CorrectionStrategy.ESCALATE_TO_HARDWARE_KB,
                description="Escalate to hardware knowledge base for constraint analysis",
                target_step=None,
                escalate=True,
                escalation_reason="Hardware constraint violation requires KB lookup",
            )

        return None

    def _from_feedback(self, feedback: dict[str, Any]) -> Correction | None:
        """Generate correction from external feedback."""
        if feedback.get("constraint_added"):
            return Correction(
                strategy=CorrectionStrategy.CONSTRAINT_INJECTION,
                description=f"Feedback: {feedback['constraint_added']}",
                target_step=None,
                constraints_to_add=[feedback["constraint_added"]],
            )

        if feedback.get("step_rejected"):
            return Correction(
                strategy=CorrectionStrategy.RETRY_WITH_DIFFERENT_APPROACH,
                description=f"Feedback: reject step - {feedback['step_rejected']}",
                target_step=None,
            )

        return None

    # ─── Step 5: Pattern Learning ────────────────────────────────────────

    def _update_learned_patterns(
        self,
        failures: list[FailureInstance],
        corrections: list[Correction],
    ) -> None:
        """Update learned patterns from this reflection session."""
        for failure in failures:
            signature = self._error_signature(failure.raw_error)

            if signature in self._learned_patterns:
                pattern = self._learned_patterns[signature]
                pattern.occurrence_count += 1
                if failure.raw_error not in pattern.example_errors:
                    pattern.example_errors.append(failure.raw_error)
            else:
                # Create new pattern
                if corrections:
                    strategy = corrections[0].strategy
                else:
                    strategy = CorrectionStrategy.NO_OP

                pattern = LearnedPattern(
                    pattern=failure.pattern,
                    symptom_signature=signature,
                    correction_strategy=strategy,
                    occurrence_count=1,
                    success_rate=0.5,
                    last_applied=datetime.now(),
                    example_errors=[failure.raw_error],
                )
                self._learned_patterns[signature] = pattern

        # Trim patterns if over limit
        if len(self._learned_patterns) > self.max_learned_patterns:
            # Remove oldest patterns
            sorted_patterns = sorted(
                self._learned_patterns.items(),
                key=lambda x: x[1].last_applied,
            )
            for sig, _ in sorted_patterns[: len(self._learned_patterns) - self.max_learned_patterns]:
                del self._learned_patterns[sig]

    # ─── Step 6: Escalation Check ──────────────────────────────────────

    def _check_escalation(
        self,
        failures: list[FailureInstance],
        corrections: list[Correction],
    ) -> tuple[bool, list[str]]:
        """Determine if this result requires escalation."""
        reasons: list[str] = []

        # Escalate if too many errors
        error_count = sum(1 for f in failures if f.severity == "error")
        if error_count >= self.escalation_error_threshold:
            reasons.append(
                f"Error count ({error_count}) exceeds threshold ({self.escalation_error_threshold})"
            )

        # Escalate if any correction has escalate flag
        for corr in corrections:
            if corr.escalate:
                reasons.append(corr.escalation_reason or corr.description)

        # Escalate on unknown patterns
        unknown_count = sum(
            1 for f in failures if f.pattern == FailurePattern.UNKNOWN
        )
        if unknown_count > 2:
            reasons.append(
                f"Too many unknown patterns ({unknown_count}), need human review"
            )

        # Escalate on hardware constraint violations
        hw_failures = [
            f for f in failures
            if f.pattern in (
                FailurePattern.HARDWARE_CONSTRAINT,
                FailurePattern.CLOCK_MISCONFIG,
                FailurePattern.REGISTER_ACCESS,
            )
        ]
        if len(hw_failures) >= 2:
            reasons.append(
                "Multiple hardware constraint violations require hardware KB review"
            )

        return len(reasons) > 0, reasons

    # ─── Step 7: Build Improvements ────────────────────────────────────

    def _build_improvements(
        self,
        failures: list[FailureInstance],
        corrections: list[Correction],
        matched_patterns: list[LearnedPattern],
    ) -> list[str]:
        """Build human-readable improvement list."""
        improvements: list[str] = []

        for corr in corrections:
            improvements.append(f"[{corr.strategy.value}] {corr.description}")

        for pattern in matched_patterns:
            improvements.append(
                f"[LEARNED] Apply known fix for {pattern.pattern.value} "
                f"(seen {pattern.occurrence_count}x)"
            )

        return improvements

    # ─── Step 8: Overall Assessment ───────────────────────────────────

    def _assess_result(
        self,
        result: dict[str, Any],
        failures: list[FailureInstance],
        corrections: list[Correction],
    ) -> str:
        """Generate overall assessment of the result."""
        success = result.get("success", False)
        error_count = sum(1 for f in failures if f.severity == "error")
        warning_count = sum(1 for f in failures if f.severity == "warning")
        confidence = result.get("confidence", 1.0)

        if success and error_count == 0 and confidence >= self.confidence_threshold:
            return "EXCELLENT — result meets all criteria"
        elif success and error_count == 0:
            return "GOOD — success with moderate confidence"
        elif success and error_count <= 2:
            return "ACCEPTABLE — success with recoverable errors"
        elif not success and error_count > 0:
            if corrections:
                return f"RECOVERABLE — {error_count} error(s), {len(corrections)} correction(s) applied"
            return f"FAILED — {error_count} error(s), no corrections available"
        elif not success and error_count == 0:
            return "UNCERTAIN — failed but no specific errors detected"
        else:
            return "NEEDS_REVIEW — unclear failure mode"

    # ─── Public API ────────────────────────────────────────────────────

    def apply_corrections(
        self,
        plan: list[dict[str, Any]],
        corrections: list[Correction],
    ) -> list[dict[str, Any]]:
        """
        Apply corrections to a plan.

        Args:
            plan: Original plan steps
            corrections: Corrections from reflection

        Returns:
            Corrected plan
        """
        if not corrections:
            return plan

        # Deep copy plan
        corrected = [dict(step) for step in plan]

        for corr in corrections:
            if corr.strategy == CorrectionStrategy.CONSTRAINT_INJECTION:
                # Inject constraints into relevant steps
                for step in corrected:
                    if "constraints" not in step:
                        step["constraints"] = []
                    step["constraints"].extend(corr.constraints_to_add)

            elif corr.strategy == CorrectionStrategy.REORDER_STEPS:
                # Reorder steps based on corrections
                for from_idx, to_idx in corr.steps_to_reorder:
                    if 0 <= from_idx < len(corrected) and 0 <= to_idx < len(corrected):
                        step = corrected.pop(from_idx)
                        corrected.insert(to_idx, step)

            elif corr.strategy == CorrectionStrategy.ADD_VALIDATION:
                # Mark steps for additional validation
                for step in corrected:
                    step["requires_validation"] = True

        return corrected

    def get_stats(self) -> dict[str, Any]:
        """Get reflection statistics."""
        pattern_counts: dict[str, int] = {}
        for p in self._learned_patterns.values():
            key = p.pattern.value
            pattern_counts[key] = p.occurrence_count

        return {
            "total_reflections": self._reflection_count,
            "learned_patterns": len(self._learned_patterns),
            "failure_history_size": len(self._failure_history),
            "patterns_by_type": pattern_counts,
        }
