"""LLM-powered fix generation using local Ollama.

This module provides intelligent fix generation for code review findings
using local LLM models (Ollama). It integrates with the existing
infrastructure/llm module but focuses on fix-specific functionality.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any, AsyncIterator, Optional

from src.infrastructure.llm.local_provider import LocalLLMProvider, LLMConfig
from src.infrastructure.llm.prompts import (
    build_finding_explanation_prompt,
    build_fix_generation_prompt,
    build_code_review_prompt,
    build_security_review_prompt,
    build_ml_review_prompt,
    ML_FIX_SYSTEM,
    SECURITY_FIX_SYSTEM,
    CODE_QUALITY_SYSTEM,
    CODE_EXPLANATION_SYSTEM,
    GENERAL_FIX_SYSTEM,
    FixPromptConfig,
)

logger = logging.getLogger(__name__)


@dataclass
class LLMFix:
    """A fix generated by the LLM."""
    old_code: str
    new_code: str
    explanation: str
    confidence: float = 0.8
    risk_level: str = "MEDIUM"
    rule_id: str = ""
    severity: str = "MEDIUM"

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "old_code": self.old_code,
            "new_code": self.new_code,
            "explanation": self.explanation,
            "confidence": self.confidence,
            "risk_level": self.risk_level,
            "rule_id": self.rule_id,
            "severity": self.severity,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "LLMFix":
        """Create from dictionary."""
        return cls(
            old_code=data.get("old_code", ""),
            new_code=data.get("new_code", data.get("fix", "")),
            explanation=data.get("explanation", ""),
            confidence=data.get("confidence", 0.8),
            risk_level=data.get("risk", data.get("risk_level", "MEDIUM")),
            rule_id=data.get("rule_id", ""),
            severity=data.get("severity", "MEDIUM"),
        )


@dataclass
class CodeFinding:
    """A finding from code analysis."""
    rule_id: str
    message: str
    severity: str = "MEDIUM"
    old_code: str = ""
    file_path: str = ""
    line: int = 0
    language: str = "python"

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "rule_id": self.rule_id,
            "message": self.message,
            "severity": self.severity,
            "old_code": self.old_code,
            "file_path": self.file_path,
            "line": self.line,
            "language": self.language,
        }


@dataclass
class LLMReviewResult:
    """Result from LLM code review."""
    findings: list[dict[str, Any]] = field(default_factory=list)
    summary: str = ""
    model_used: str = ""
    processing_time: float = 0.0

    @property
    def has_findings(self) -> bool:
        """Check if there are any findings."""
        return len(self.findings) > 0

    def get_critical_findings(self) -> list[dict[str, Any]]:
        """Get only critical severity findings."""
        return [f for f in self.findings if f.get("severity") == "CRITICAL"]

    def get_high_findings(self) -> list[dict[str, Any]]:
        """Get only high severity findings."""
        return [f for f in self.findings if f.get("severity") == "HIGH"]


class LLMFixEngine:
    """Generate intelligent fixes using local LLM.

    This engine uses Ollama to:
    - Generate fixes for code findings
    - Explain code issues
    - Perform targeted code reviews
    - Suggest security improvements

    Usage:
        engine = LLMFixEngine(model="llama3")
        fix = await engine.generate_fix(finding, context)
    """

    def __init__(
        self,
        model: str = "llama3",
        base_url: str = "http://localhost:11434/api",
        temperature: float = 0.3,
        max_tokens: int = 2048,
    ):
        """Initialize the fix engine.

        Args:
            model: Ollama model name
            base_url: Ollama server URL
            temperature: Sampling temperature (lower = more deterministic)
            max_tokens: Maximum tokens to generate
        """
        self.model = model
        self.base_url = base_url
        self.temperature = temperature
        self.max_tokens = max_tokens
        self._provider: Optional[LocalLLMProvider] = None

    async def _get_provider(self) -> LocalLLMProvider:
        """Get or create the LLM provider."""
        if self._provider is None:
            config = LLMConfig(
                base_url=self.base_url,
                model=self.model,
                temperature=self.temperature,
                max_tokens=self.max_tokens,
            )
            self._provider = LocalLLMProvider(config)
        return self._provider

    async def generate_fix(
        self,
        finding: dict[str, Any],
        context: str = "",
        fix_type: str = "general"
    ) -> Optional[LLMFix]:
        """Generate a fix for a finding using LLM.

        Args:
            finding: Finding dictionary with message, rule_id, etc.
            context: Additional code context
            fix_type: Type of fix (general, ml, security, quality)

        Returns:
            LLMFix object if successful, None otherwise
        """
        provider = await self._get_provider()

        try:
            if not await provider.is_available():
                logger.warning(
                    "Ollama not available. Install with: ollama pull %s",
                    self.model
                )
                return None

            # Select appropriate system prompt
            system_prompts = {
                "ml": ML_FIX_SYSTEM,
                "security": SECURITY_FIX_SYSTEM,
                "quality": CODE_QUALITY_SYSTEM,
            }
            system = system_prompts.get(fix_type, GENERAL_FIX_SYSTEM)

            # Build prompt
            prompt = build_fix_generation_prompt(finding, context)
            response = await provider.generate(prompt, system)

            # Parse JSON response
            data = self._parse_fix_response(response)
            if data:
                return LLMFix(
                    old_code=finding.get("old_code", ""),
                    new_code=data.get("new_code", ""),
                    explanation=data.get("explanation", ""),
                    confidence=data.get("confidence", 0.8),
                    risk_level=data.get("risk", "MEDIUM"),
                    rule_id=finding.get("rule_id", ""),
                    severity=finding.get("severity", "MEDIUM"),
                )

        except json.JSONDecodeError as e:
            logger.warning("Failed to parse LLM response as JSON: %s", e)
        except Exception as e:
            logger.error("LLM fix generation failed: %s", e)

        return None

    async def explain_finding(
        self,
        finding: dict[str, Any],
        context: str = ""
    ) -> Optional[str]:
        """Get detailed explanation of a finding.

        Args:
            finding: Finding dictionary
            context: Additional code context

        Returns:
            Explanation text if successful
        """
        provider = await self._get_provider()

        try:
            if not await provider.is_available():
                return None

            prompt = build_finding_explanation_prompt(finding, context)
            response = await provider.generate(prompt, CODE_EXPLANATION_SYSTEM)
            return response.strip()

        except Exception as e:
            logger.error("LLM explanation failed: %s", e)
            return None

    async def review_code(
        self,
        code: str,
        review_type: str = "general",
        language: str = "python"
    ) -> Optional[LLMReviewResult]:
        """Perform code review using LLM.

        Args:
            code: Code to review
            review_type: Type of review (general, security, ml)
            language: Programming language

        Returns:
            LLMReviewResult with findings
        """
        provider = await self._get_provider()

        try:
            if not await provider.is_available():
                return None

            # Select appropriate prompt
            prompt_builders = {
                "security": build_security_review_prompt,
                "ml": build_ml_review_prompt,
            }
            builder = prompt_builders.get(review_type, build_code_review_prompt)
            prompt = builder(code, language)

            # Select system prompt
            system_prompts = {
                "security": SECURITY_FIX_SYSTEM,
                "ml": ML_FIX_SYSTEM,
                "quality": CODE_QUALITY_SYSTEM,
            }
            system = system_prompts.get(review_type, CODE_QUALITY_SYSTEM)

            response = await provider.generate(prompt, system)
            findings = self._parse_findings_response(response)

            return LLMReviewResult(
                findings=findings,
                summary=f"Found {len(findings)} issues",
                model_used=self.model,
            )

        except Exception as e:
            logger.error("LLM code review failed: %s", e)
            return None

    async def stream_fix(
        self,
        finding: dict[str, Any],
        context: str = ""
    ) -> AsyncIterator[str]:
        """Stream a fix generation.

        Args:
            finding: Finding dictionary
            context: Additional code context

        Yields:
            Text chunks as they arrive
        """
        provider = await self._get_provider()

        try:
            if not await provider.is_available():
                yield "Error: Ollama not available"
                return

            prompt = build_fix_generation_prompt(finding, context)
            async for chunk in provider.generate_stream(prompt, GENERAL_FIX_SYSTEM):
                yield chunk

        except Exception as e:
            logger.error("LLM stream fix failed: %s", e)
            yield f"Error: {e}"

    def _parse_fix_response(self, response: str) -> Optional[dict[str, Any]]:
        """Parse LLM fix response.

        Args:
            response: Raw LLM response

        Returns:
            Parsed dictionary or None
        """
        try:
            # Try direct JSON parse
            return json.loads(response)
        except json.JSONDecodeError:
            pass

        # Try to extract JSON from response
        import re
        json_pattern = r'\{[^{}]*\}'
        matches = re.findall(json_pattern, response, re.DOTALL)
        for match in matches:
            try:
                return json.loads(match)
            except json.JSONDecodeError:
                continue

        return None

    def _parse_findings_response(self, response: str) -> list[dict[str, Any]]:
        """Parse LLM findings response.

        Args:
            response: Raw LLM response

        Returns:
            List of finding dictionaries
        """
        try:
            # Try direct JSON parse
            parsed = json.loads(response)
            if isinstance(parsed, list):
                return parsed
            return [parsed]
        except json.JSONDecodeError:
            pass

        # Try to extract JSON array
        import re
        array_pattern = r'\[[\s\S]*\]'
        matches = re.findall(array_pattern, response)
        for match in matches:
            try:
                parsed = json.loads(match)
                if isinstance(parsed, list):
                    return parsed
            except json.JSONDecodeError:
                continue

        return []

    async def is_available(self) -> bool:
        """Check if the LLM provider is available.

        Returns:
            True if Ollama is running and model is available
        """
        try:
            provider = await self._get_provider()
            return await provider.is_available()
        except Exception:
            return False

    async def get_available_models(self) -> list[str]:
        """Get list of available models.

        Returns:
            List of model names
        """
        try:
            provider = await self._get_provider()
            models = await provider.list_models()
            return [m.name for m in models]
        except Exception:
            return []


# Convenience function for simple usage
async def generate_fix(
    finding: dict[str, Any],
    context: str = "",
    model: str = "llama3"
) -> Optional[LLMFix]:
    """Generate a fix for a finding.

    Args:
        finding: Finding dictionary
        context: Additional code context
        model: Ollama model name

    Returns:
        LLMFix if successful
    """
    engine = LLMFixEngine(model=model)
    return await engine.generate_fix(finding, context)


async def explain_issue(
    finding: dict[str, Any],
    context: str = "",
    model: str = "llama3"
) -> Optional[str]:
    """Explain a code issue.

    Args:
        finding: Finding dictionary
        context: Additional code context
        model: Ollama model name

    Returns:
        Explanation text if successful
    """
    engine = LLMFixEngine(model=model)
    return await engine.explain_finding(finding, context)
