apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aisupport

resources:
  - redis-configmap.yaml
  - redis-secrets.yaml
  - redis-statefulset.yaml
  - redis-sentinel-statefulset.yaml

commonLabels:
  app.kubernetes.io/name: aisupport
  app.kubernetes.io/component: redis

configMapGenerator:
  - name: redis-config
    behavior: replace
    envs:
      - redis.env

secretGenerator:
  - name: redis-secrets
    behavior: replace
    envs:
      - redis-secrets.env
    type: Opaque
  - name: redis-certs
    behavior: replace
    files:
      - certs/redis.crt
      - certs/redis.key
      - certs/ca.crt
    type: kubernetes.io/tls
